# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    type: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '10.22.0'
    - run: npm install
    - run: npm run build
    - run: npm run dist
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: dist/
  
